//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPNFCWineSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InactiveWine
    {
        public int WID { get; set; }
        public int WineCategoryID { get; set; }
        public string WineTitle { get; set; }
        public int WineStatusID { get; set; }
        public string WineDescription { get; set; }
        public string Vintage { get; set; }
        public System.DateTime LastTransDate { get; set; }
        public string username { get; set; }
        public double Discount { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public int Price { get; set; }
        public string LastSupplyChain { get; set; }
        public Nullable<int> TagID { get; set; }
        public string Producer { get; set; }
        public byte[] WinePic { get; set; }
        public string WineTransactionHistory { get; set; }
        public System.DateTime DateOfProduction { get; set; }
        public Nullable<int> RejectionID { get; set; }
        public Nullable<System.DateTime> RejectionDate { get; set; }
    
        public virtual ActiveWine ActiveWine { get; set; }
        public virtual Rejection Rejection { get; set; }
        public virtual WineCategory WineCategory { get; set; }
        public virtual WineStatu WineStatu { get; set; }
    }
}
