//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPNFCWineSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rejection
    {
        public Rejection()
        {
            this.ActiveWines = new HashSet<ActiveWine>();
            this.InactiveWines = new HashSet<InactiveWine>();
        }
    
        public int RejectionID { get; set; }
        public string RejectionReason { get; set; }
    
        public virtual ICollection<ActiveWine> ActiveWines { get; set; }
        public virtual ICollection<InactiveWine> InactiveWines { get; set; }
    }
}
