//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPNFCWineSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyChain
    {
        public SupplyChain()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int SupplyID { get; set; }
        public string Address { get; set; }
        public string PartnerName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Email { get; set; }
        public int MarketValue { get; set; }
        public string Nationality { get; set; }
        public string PastTransactionSummary { get; set; }
        public string username { get; set; }
        public string contactPic { get; set; }
        public int TrustStatusID { get; set; }
        public System.DateTime DateOfEstablishment { get; set; }
        public Nullable<int> WID { get; set; }
        public int CompanySize { get; set; }
    
        public virtual ActiveWine ActiveWine { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual TrustStatu TrustStatu { get; set; }
    }
}
